// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbq

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	UserID      string
	HashedToken string
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

type Report struct {
	ID                   string
	UserID               string
	ReportType           string
	OutputFilePath       sql.NullString
	DownloadUrl          sql.NullString
	DownloadUrlExpiresAt sql.NullTime
	ErrorMessage         sql.NullString
	CreatedAt            time.Time
	StartedAt            sql.NullTime
	FailedAt             sql.NullTime
	CompletedAt          sql.NullTime
}

type User struct {
	ID             string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
}
